# Site settings
title: twang.fr
email: pierrefenoll@gmail.com
#twitter_username: jekyllrb
github_username: fenollp
full_name: Pierre Fenoll
description: "Twang • Pierre Fenoll's very own company"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://twang.fr" # the base hostname & protocol for your site
permalink: /:title/

google_analytics_id: UA-72467418-1

exclude: ["Makefile", "CNAME"]

# Build settings
markdown: kramdown

highlighter: pygments

kramdown:
  input: GFM
